# Generated by Django 4.2.7 on 2023-11-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Busqueda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo_uno", models.CharField(max_length=100)),
                ("campo_dos", models.IntegerField()),
            ],
        ),
    ]
